Donate:
  '10000': 'tst give %player% 10000'
  '20000': 'tst give %player% 20000'
  '50000': 'tst give %player% 50000'
  '100000': 'tst give %player% 100000'
  '200000': 'tst give %player% 200000'
  '500000': 'tst give %player% 500000'
Help:
  - '&e/napthesync &a<UUID> <Mệnh giá> &f- Lưu yêu cầu nạp thẻ cho người chơi.'
  - '&e/napthesync &ahelp &f- Hiển thị phần trợ giúp này.'
  - '&e/napthesync &ahistory &a<Player> &f- Hiển thị lịch sử nạp thẻ của người chơi.'
  - '&e/napthesync &areload &f- Reload lại config của plugin.'
Messages:
  param_error: '&eNapThe &3| &cLỗi: &fCú pháp lệnh không đầy đủ! Vui lòng kiểm tra lại!'
  uuid_error: '&eNapThe &3| &cLỗi: &fKhông có người chơi nào có mã &eUUID &fnhư thế!'
  integer_error: '&eNapThe &3| &cLỗi: &fVui lòng nhập mệnh giá hợp lệ!'
  no_history: '&eNapThe &3| &cLỗi: &fNgười dùng này hình như chưa nạp thẻ lần nào :/'
  history_show: '- &e[amount] VNĐ &f- &a[time]'
  reloaded: '&eNapThe &3| &aGhi chú: &fPlugin đã hoàn tất reload!'
  page-next: '&a-->'
  page-next-hover: '&fTrang &atiếp'
  page-previous: '&a<--'
  page-previous-hover: 'Trang &btrước'
  page-num: ' &f<Trang &a[now]/[max]&f> '